core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.products, name='products'),
    path('products/<slug:slug>', views.product, name='product'),
    path('news/', views.news, name='news'),
    path('news/<slug:slug>', views.post, name='post'),
    path('about', views.about, name='about'),
    path('geo', views.geo, name='geo'),
    path('payment', views.payment, name='payment'),
    path('price', views.price, name='price'),
    path('feedback', views.feedback, name='feedback'),
]

mtllst/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'MTLLST Admin'
admin.site.site_title = 'MTLLST Admin Portal'
admin.site.index_title = 'Welcome to MTLLST Portal'

core/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from tinymce.models import HTMLField
from PIL import Image, ImageOps


# Create your models here.

class Product(models.Model):
    title = models.CharField(max_length=250, unique=True,
        verbose_name='Название')
    slug = models.SlugField(max_length=250, unique=True,
        verbose_name='URL')
    image = models.ImageField(upload_to='images', blank=True,
        verbose_name='Изображение')

    class Meta:
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return reverse('core:product', args=[self.slug])

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        image = Image.open(self.image)
        image.save(self.image.path, quality=settings.IMG_QUALITY,
            optimize=True)

    def __str__(self):
        return self.title

class Item(models.Model):
    text = models.CharField(max_length=250, blank=True, null=True,
        verbose_name = 'Наименование')
    product = models.ForeignKey(Product, on_delete=models.CASCADE,
        related_name='items')

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Изделия'
    
    def __str__(self):
        return self.text

class Post(models.Model):
    title = models.CharField(max_length=250, unique=True,
        verbose_name='Заголовок')
    slug = models.SlugField(max_length=250, unique=True,
        verbose_name='URL')
    text = HTMLField(verbose_name='Текст')
    added = models.DateTimeField(auto_now_add=True)
    cover = models.ImageField(upload_to='images', blank=True,
        verbose_name='Обложка')

    def get_absolute_url(self):
        return reverse('core:post', args=[self.slug])

    class Meta:
        verbose_name = 'Статью'
        verbose_name_plural = 'Статьи'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        image = Image.open(self.cover)
        image.save(self.cover.path, quality=settings.IMG_QUALITY,
            optimize=True)

    def __str__(self):
        return self.title

core/forms.py
from django import forms
from django.core.validators import RegexValidator

class FeedbackForm(forms.Form):
    phoneNumberRegex = RegexValidator(regex=r'^\+?1?\d{8,15}$',
        message='Введите корректный номер телефона')
    name = forms.CharField(max_length=25, label='Ваше имя',
        widget=forms.TextInput(attrs={'class': 'order-inner__input'}))
    phone = forms.CharField(max_length=16, label='Ваш телефон',
        widget=forms.TextInput(attrs={'class': 'order-inner__input'}),
        validators=[phoneNumberRegex])
    email = forms.EmailField(label='Email адрес',
        widget=forms.TextInput(attrs={'class': 'order-inner__input'}))
    text = forms.CharField(label=' Ваше сообщение',
        widget=forms.Textarea(attrs={'class': 'order-inner__text-area'}))

core/views.py
from django.shortcuts import render, redirect,  get_object_or_404
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.contrib import messages
from django.conf import settings
from .models import Product, Post
from .forms import FeedbackForm

# Create your views here.

def home(request):
    products = Product.objects.all()[:3]
    return render(request, 'core/home.html', {'products': products})

def products(request):
    products = Product.objects.all()
    return render(request, 'core/products.html', {'products': products})

def product(request, slug):
    product = get_object_or_404(Product, slug=slug)
    return render(request, 'core/product.html', {'product': product})

def news(request):
    posts = Post.objects.order_by('-added')
    return render(request, 'core/news.html', {'posts': posts})

def post(request, slug):
    post = get_object_or_404(Post, slug=slug)
    return render(request, 'core/post.html', {'post': post})

def about(request):
    return render(request, 'core/about.html')

def geo(request):
    return render(request, 'core/geo.html')

def payment(request):
    return render(request, 'core/payment.html')

def price(request):
    return render(request, 'core/price.html')

def feedback(request):
    if request.method == 'POST':
        if 'modal' in request.POST:
            form = FeedbackForm(request.POST, prefix='modal')
        else:
            form = FeedbackForm(request.POST, prefix='footer')
        if form.is_valid():
            cd = form.cleaned_data
            subject = f'[MTLLST] User {cd["name"]} send mail'
            message = render_to_string('core/email.html', {'data': cd})
            send_mail(subject, message, settings.EMAIL_HOST_USER,
                [settings.EMAIL_HOST_USER])
            messages.info(request, 'Сообщение успешно отправлено')
        else:
            for field in form:
                for error in field.errors:
                    messages.error(request, error)
        return redirect(request.POST.get('next'))
    return redirect('/')

core/templates/core/about.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}О нас{%endblock%}

{% block content %}
      <div class="container">
        <section class="about">
          <h2>О заводе</h2>
          <div class="about-inner">
            <div class="about-inner__img">
              <img src="{% static 'core/images/logo.svg' %}" width="316" height="342"  alt="Логотип">
            </div>
            <p class="about-inner__text">
              "Завод Металлооснастки" – ветеран в отрасли производства высококачественного
              технологического оборудования для получения железобетонных изделий.
              <br><br><span class="text-medium">ГОСТ 25781-2018, ГОСТ 25878-85, ГОСТ 27204-87,
              ГОСТ 28715-90</span> – основополагающие документы ведущей деятельности компании.
              <br><br>Металлоформы (групповые, универсальные, переналаживаемые, многоместные, вагонетки)
              изготавливаем как по разработанной конструкторским отделом завода проектной документации,
              так и по предоставленным заказчиком чертежам. <br><br>В настоящее время нами освоена такая
              продукция как: вибростолы, вибротумбы, кассетные установки, телеги самоходные, столы,
              магнитная быстросъемная бортовая оснастка и иное оборудование для предприятий по
              производству железобетонных изделий.
              <br><br>Накопив колоссальный опыт, располагая штатом высококвалифицированных специалистов,
              готовы к дальнейшему росту и освоению новых видов изделий.
              <br><br>Наш завод уникален, и мы, его сотрудники, увлеченные своим делом, радеем о
              его развитии и престиже.
              <br><br>«Завод Металлооснастки» - достойный профессиональный партнер!
            </p>
            <br><br>
            <p class="about-inner__text about-inner__owner">
              <br>Директор ООО "Завод Металлооснастки"
              <br><span class="text-medium">Возмилов Игорь Владимирович</span>
            </p>
          </div>
        </section>
      </div>
{% endblock %}

core/templates/core/base.html
{% load static %}
{% load compress %}
{% load core_tags %}
{% feedback_form 'modal' as modal_form %}
{% feedback_form 'footer' as footer_form %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock %}">
    {% compress css %}
    <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    {% endcompress %}
    <title>{% block title %}{% endblock %}</title>
    <link type="image/x-icon" href=" {% static 'core/images/favicon-32x32.png' %}" rel="shortcut icon">
  </head>
  <body>
    <main>
      {% if messages %}
      {% for message in messages %}
      <div>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% else %}
        <div class="alert alert-success alert-dismissible" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}
      </div>
      {% endfor %}
      {% endif %}
      <header class="header">
        <div class="container">
          <div class="header__top">
            <div class="header__top-item">ООО «ЗАВОД МЕТАЛЛООСНАСТКИ»</div>
            <div class="header__top-item"><span class="address">644085, г. Омск, пр. Мира, д. 185, корп. 3</span></div>
            <div class="header__top-item">
              <div class="numbers">
                <div class="numbers__item"><a href="tel:83812267489">8 3812 26 74 89</a></div>
                <div class="numbers__item"><a href="tel:83812267669">8 3812 26 76 69</a></div>
              </div>
            </div>
          </div>
          <div class="header__bottom">
            <div class="header__bottom-item">
              <button class="primary-button" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Оставить заказ
              </button>
            </div>
            <div class="header__bottom-item">
              <nav class="nav">
                <ul class="menu">
                  {% url 'core:home' as url %}
                  <li class="menu__item {% if request.path == url %}menu__item_active{% endif %}">
                      <a href="{{ url }}" class="menu__item-link">Главная</a>
                  </li>
                  {% url 'core:products' as url %}
                  <li class="menu__item {% if url in request.path %}menu__item_active{% endif %}">
                      <a href="{{ url }}" class="menu__item-link">Продукция</a>
                  </li>
                  {% url 'core:news' as url %}
                  <li class="menu__item {% if url in request.path %}menu__item_active{% endif %}">
                      <a href="{{ url }}" class="menu__item-link">Новости</a>
                  </li>
                  {% url 'core:about' as url %}
                  <li class="menu__item {% if request.path == url %}menu__item_active{% endif %}">
                      <a href="{{ url }}" class="menu__item-link">О нас</a>
                  </li>
                  <li class="menu__item">
                    <div class="menu__item-link">Прочее
                      <object type="image/svg+xml" data="{% static 'core/images/angle-arrow-down.svg' %}"></object>
                      <div class="dropdown-fix"></div>
                    </div>
                    <div class="dropdown">
                        <a href="{% url 'core:geo' %}">География поставок</a>
                        <a href="{% url 'core:payment' %}">Оплата и доставка</a>
                        <a href="{% url 'core:price' %}">Цены</a>
                    </div>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        </div>
        <div class="burger">
          <button class="burger__btn" aria-label="Навигация">
            <span></span>
            <span></span>
            <span></span>
          </button>
          <nav class="burger__nav">
              <ul>
                <li><a href="{% url 'core:home' %}">Главная</a></li>
                <li><a href="{% url 'core:products' %}">Продукция</a></li>
                <li><a href="{% url 'core:news' %}">Новости</a></li>
                <li><a href="{% url 'core:about' %}">О нас</a></li>
                <li><a href="{% url 'core:geo' %}">География поставок</a></li>
                <li><a href="{% url 'core:payment' %}">Оплата и доставка</a></li>
                <li><a href="{% url 'core:price' %}">Цены</a></li>
              </ul>
          </nav>
        </div>
      </header>
      {% block content %}{% endblock %}
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="modal-body">
              <div class="order-modal">
                <div class="order-inner">
                  <div class="order-inner__h">ОСТАВИТЬ ЗАКАЗ</div>
                  <a href="#" class="close" data-bs-dismiss="modal"></a>
                  <p class="order-inner__text">Напишите нам информацию о заказе и мы с Вами свяжемся.</p>
                  <form action="{% url 'core:feedback' %}" method="POST" class="order-inner__form">
                    {{ modal_form.as_p }}
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <button class="small-btn" name="modal">Отправить</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
    <footer class="footer">
      <div class="footer-top">
        <div class="container">
          <div class="go-back">
            <a href="#" class="go-back__text">
              ВЕРНУТЬСЯ
              <object type="image/svg+xml" data="{% static 'core/images/arrow-top.svg' %}" aria-label="Назад"></object>
            </a>
          </div>
          <div class="footer-info">
            <ul class="footer-top__list">
              <li class="footer-top__list-header">КОНТАКТЫ</li>
              <li class="footer-top__list-item">
                <object type="image/svg+xml" data="{% static 'core/images/point.svg' %}" aria-label="Адрес"></object> 644085, г. Омск,
                <br>пр. Мира д. 185, корп. 3
              </li>
              <li class="footer-top__list-item">
                <object type="image/svg+xml" data="{% static 'core/images/mail.svg' %}" aria-label="Почта"></object> metallist-2000@yandex.ru
              </li>
              <li class="footer-top__list-item">
                <object type="image/svg+xml" data="{% static 'core/images/phone.svg' %}" aria-label="Телефон"></object> 8 (3812) 26-74-89
              </li>
              <li class="footer-top__list-item">
                <object type="image/svg+xml" data="{% static 'core/images/phone.svg' %}" aria-label="Телефон"></object> 8 (3812) 26-76-69
              </li>
            </ul>
            <ul class="footer-top__list">
              <li class="footer-top__list-header">СОЦИАЛЬНЫЕ СЕТИ</li>
              <li id="telega" class="footer-top__list-item">
                <a href="https://www.t.me/omsk_metalloosnastka" target="_blank">Telegram</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-bottom__wrapper">
        <div class="container">
          <div class="footer-bottom">
            <div class="footer-bottom__item">ООО «Завод Металлооснастки» © {% now "Y" %}</div>
            <div class="footer-bottom__item">
              <a href="http://squozdigital.ru/" target="_blank">
                 Создание сайта - <span id="squoz">SQUOZ DIGITAL</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </footer>
    {% compress js %}
    <script src="{% static 'core/js/app.min.js' %}"></script>
    {% endcompress %}
  </body>
</html>

core/templates/core/email.html
Сообщение от {{ data.name }}

Телефон: {{ data.phone }}
Почта: {{ data.email }}

{{ data.text }}

core/templates/core/geo.html
{% extends 'core/base.html' %}

{% block title %}География доставок{% endblock %}

{% block content %}
      <div class="container">
        <section class="geo-sec">
          <h2>География доставок</h2>
          <div class="price-sec__item">
            <p class="geo-sec__text">
              Принимаем заказы с любых регионов России и стран ближнего зарубежья.
            </p>
          </div>
        </section>
      </div>
{% endblock %}

core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}

{% block description %}
Завод «МЕТАЛЛООСНАСТКИ» производит продукцию для отраслей гражданского строительства,
нефтегазовой промышленности, железнодорожного строительства, электросетевого строительства,
дорожного и аэродромного строительства и других.
Вы можете ознакомиться со всей нашей продукцией и оставить заказ.
{% endblock %}
{% block title %}ООО «ЗАВОД МЕТАЛЛООСНАСТКИ»{% endblock %}

{% block content %}
      <!-- banner -->
      <div class="container">
        <section class="banner">
          <h6>Банер</h6>
          <p class="banner__text">Качество, наработанное годами</p>
        </section>
      </div>
      <!-- mom -->
      <div class="container">
        <section class="mom">
          <h6>Описание</h6>
          <div class="mom__item">
            <p class="primary-text">                  
           Сплоченная команда единомышленников «завода Металлооснастки» приветствует вас и приглашает к дальнейшему сотрудничеству.
	    </p>
          </div>
  	   <!-- <div class="mom__item">
            <div class="mom__item-media">
              <iframe src="https://www.youtube.com/embed/2Ima9QohipA?" title="YouTube video player" frameborder="0"
		allow="accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen></iframe>
            </div>
	   </div> -->
        </section>
      </div>
      <!-- advantages -->
      <div class="container">
        <hr>
        <section class="advantages">
          <h2>Производство металлоформ для ЖБИ и металлоконструкций</h2>
          <div class="advantages-inner">
            <div class="advantages__item">
              <div class="advantages__item-img">
                <img src="{% static 'core/images/img-1.png' %}" width="176" height="176" alt="Опыт">
              </div>
              <div class="advantages__item-text">50 лет в отрасли</div>
            </div>
            <div class="advantages__item">
              <div class="advantages__item-img">
                <img src="{% static 'core/images/img-2.png' %}" width="184" height="176" alt="Маштаб">
              </div>
              <div class="advantages__item-text">8.5 тыс. м² производственных площадей</div>
            </div>
            <div class="advantages__item">
              <div class="advantages__item-img">
                <img src="{% static 'core/images/img-3.png' %}" width="182" height="176" alt="Контроль">
              </div>
              <div class="advantages__item-text">Контроль ОТК</div>
            </div>
            <div class="advantages__item">
              <div class="advantages__item-img">
                <img src="{% static 'core/images/img-4.png' %}" width="181" height="176" alt="Гарантии">
              </div>
              <div class="advantages__item-text">Гарантии производителя</div>
            </div>
          </div>
        </section>
      </div>
      <!-- about -->
      <div class="container">
        <hr>
        <section class="about">
          <h2>О заводе</h2>
          <p class="primary-text">
            Общество с ограниченной ответственностью «Завод Металлооснастки» образовано
            в 2000 году на базе завода Металлист, который ранее именовался Николаевским
            ремонтно-механическим заводом и являлся одним из старейших предприятий в стройиндустрии.
          </p>
          <div class="blue-link">
            <a class="link-text" href="{% url 'core:about' %}">Узнать больше</a>
            <object type="image/svg+xml" data="{% static 'core/images/arrow-right.svg' %}" aria-label="Подробнее"></object>
          </div>
        </section>
      </div>
      <!-- production -->
      <div class="container">
        <hr>
        <section class="production">
          <h2>Что мы изготавливаем?</h2>
          <div class="production__item-wrapper">
            <div class="row row-cols-1  row-cols-sm-2 row-cols-md-3">
              {% for product in products %}
              <div class="col">
                <a href="{{ product.get_absolute_url }}" class="production__item">
                  <div class="production__item-image">
                    {% if product.image %}
                    <img src="{{ product.image.url }}" width="420" height="420" alt="{{ product.title }}">
                    {% else %}
                    <img src="{% static 'core/images/default.jpg' %}" width="420" height="420" alt="{{ product.title }}">
                    {% endif %}
                  </div>
                  <div class="production__item-text">{{ product.title }}</div>
                </a>
              </div>
              {% endfor %}
            </div>
          </div>
          <div class="production__link">
            <div class="blue-link">
              <a class="link-text" href="{% url 'core:products' %}">Вся продукция</a>
              <object type="image/svg+xml" data="{% static 'core/images/arrow-right.svg' %}" aria-label="Подробнее"></object>
            </div>
          </div>
        </section>
      </div>
      <!-- order -->
      <section class="order">
        <h6>Оставить заказ</h6>
        <div class="container">
          <div class="order-inner">
            <div class="order-inner__h">ОСТАВИТЬ ЗАКАЗ</div>
            <p class="order-inner__text">Напишите нам информацию о заказе и мы с Вами свяжемся.</p>
            <form action="{% url 'core:feedback' %}" method="POST" class="order-inner__form">
              <div class="order-inner__form-inputs">
                <label for="{{ footer_form.name.id_for_label }}">
                  {{ footer_form.name.label }}:{{ footer_form.name }}
                </label>
                <label for="{{ footer_form.phone.id_for_label }}">
                  {{ footer_form.phone.label }}:{{ footer_form.phone }}
                </label>
                <label for="{{ footer_form.email.id_for_label }}">
                  {{ footer_form.email.label }}:{{ footer_form.email }}
                </label>
              </div>
              <label for="{{ footer_form.text.id_for_label }}">
                {{ footer_form.text.label }}:{{ footer_form.text }}
              </label>
              <input type="hidden" name="next" value="{{ request.path }}">
              {% csrf_token %}
              <button class="small-btn" name="footer">Отправить</button>
            </form>
          </div>
        </div>
      </section>
{% endblock %}

core/templates/core/news.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Новости{% endblock %}

{% block content %}
      <div class="container">
        <section class="news-sec">
          <h2>Новости</h2>
          <div class="news">
            {% for post in posts %}
            <div class="news__item">
              <div class="news__item-info-wrapper">
                <div class="news__item-h">
                  <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                  </a>
                </div>
                <div class="news__item-text">
                  {{ post.text|truncatewords_html:30|safe }}
                </div>
                <div class="news__item-date">
                  {{ post.added|date:'d b Y в H:i' }}
                </div>
              </div>
              <div class="news__item-media">
                {% if post.cover %}
                <img src="{{ post.cover.url }}" width="700" height="448" alt="{{ post.title }}">
                {% else %}
                <img src="{% static 'core/images/default.jpg' %}" width="420" height="420" alt="{{ post.title }}">
                {% endif %}
              </div>
            </div>
            {% endfor %}
          </div>
        </section>
      </div>
{% endblock %}

core/templates/core/payment.html
{% extends 'core/base.html' %}

{% block title %}Оплата и доставка{% endblock %}

{% block content %}
      <div class="container">
        <section class="payment">
          <h2>Оплата и доставка</h2>
          <h4>
            Оплата осуществляется безналичным перечислением на счет предприятия по
            следующим реквизитам:
          </h4>
          <p class="payment__text">
            <span class="text-medium">Полное наименование:</span> ОБЩЕСТВО С ОГРАНИЧЕННОЙ
            ОТВЕТСТВЕННОСТЬЮ "ЗАВОД МЕТАЛЛООСНАСТКИ"
            <br><span class="text-medium">Юридический адрес:</span> 644085, Омская область, город Омск, проспект
            Мира, дом 185 корпус 3, литера б
            <br><span class="text-medium">Директор на основании Устава:</span> Возмилов Игорь Владимирович
            <br><span class="text-medium">ИНН:</span> 5501184750
            <br><span class="text-medium">КПП:</span> 550101001
            <br><span class="text-medium">ОГРН:</span> 1175543031278
            <br><span class="text-medium">ОКПО:</span> 09478097
            <br><span class="text-medium">р/счет:</span> 40702810223440000748
            <br><span class="text-medium">кор/счет:</span> 30101810600000000774
            <br><span class="text-medium">Банк:</span> Филиал "Новосибирский" АО "Альфа-банк"
            <br><span class="text-medium">БИК:</span> 045004774
          </p>
          <p class="payment__text payment__text-bottom">
            Предоставляется пакет бухгалтерских документов: договор, счет-фактура, акт
            выполненных работ или накладная и иное.
            <br><span class="text-medium">Отправка продукции осуществляется любыми видами транспорта.</span>
          </p>
        </section>
      </div>
{% endblock %}

core/templates/core/post.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
      <div class="container">
        <section class="news-more-sec">
          <h2>{{ post.title }}</h2>
          <div class="news-more-sec__date">{{ post.added|date:'d b Y в H:i' }}</div>
          <div class="news-inner">
            <div class="news-inner__text">
              {{ post.text|safe }}
            </div>
            <div class="news-inner__imgs">
              {% if post.cover %}
              <div class="news-inner__media">
                <img src="{{ post.cover.url }}" width="460" height="294" alt="{{ post.title }}">
              </div>
            {% endif %}
            </div>
          </div>
        </section>
      </div>
{% endblock %}

core/templates/core/price.html
{% extends 'core/base.html' %}

{% block title %}Цены{% endblock %}

{% block content %}
      <div class="container">
        <section class="price-sec">
          <h2>Цены</h2>
          <div class="price-sec__item">
            <p class="price-sec__text">
              Ценовая политика предприятия складывается из объема и трудоемкости заказа.
              Менеджер завода по техническому заданию (запросу) клиента в кратчайшие сроки предоставит
              коммерческое предложение. Предусмотрена гибкая система скидок.
            </p>
          </div>
        </section>
      </div>
{% endblock %}

core/templates/core/product.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}{{ product.title }}{% endblock %}

{% block content %}
      <div class="container">
        <section class="production-more-sec">
          <h2>{{ product.title }}</h2>
          <div class="production-inner">
            <div class="uls">
              <ul class="production-inner__list">
                {% for item in product.items.all %}
                <li class="production-inner__list-item">{{ item.text }}</li>
                {% endfor %}
              </ul>
            </div>
            <div class="production-inner__img">
              {% if product.image %}
              <img src="{{ product.image.url }}" width="310" height="223" alt="{{ product.title }}">
              {% else %}
              <img src="{% static 'core/images/default.jpg' %}" width="310" height="223" alt="{{ product.title }}">
              {% endif %}
            </div>
          </div>
        </section>
      </div>
{% endblock %}

core/templates/core/products.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Продукция{% endblock %}

{% block content %}
      <div class="container">
        <section class="production-sec">
          <h2>Продукция</h2>
          <div class="production-page">
            <div class="production-page__row row">
            {% for product in products %}
              <a href="{{ product.get_absolute_url }}" class="production-page__card col">
                <div class="production-page__card-img">
                  {% if product.image %}
                  <img src="{{ product.image.url }}" width="310" height="223" alt="{{ product.title }}">
                  {% else %}
                  <img src="{% static 'core/images/default.jpg' %}" width="310" height="223" alt="{{ product.title }}">
                  {% endif %}
                </div>
                <div class="production-page__card-text">
                  {{ product.title }}
                </div>
              </a>
            {% endfor %}
            </div>
          </div>
        </section>
      </div>
{% endblock %}